index:
    path: /
    controller: App\Controller\StatController::index

getDepartement:
  path:     /departements/view/{code}
  controller: App\Controller\StatController::getDepartement
  methods: GET

